apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ygss-backend:latest        # ← Jenkins가 이 한 줄만 v태그로 치환
          imagePullPolicy: IfNotPresent     # ← 로컬 import 전략과 궁합 OK
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secrets       # ← Jenkins가 런타임 생성
            - configMapRef:
                name: backend-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_HOST
              value: "172.26.7.217"
            - name: MYSQL_DATABASE
              value: "ygss"
            - name: MYSQL_USER
              value: "admin"
            - name: REDIS_HOST
              value: "172.26.7.217"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          # 준비되면 헬스체크도 추가 권장 (예: /infra 또는 /actuator/health)
          # readinessProbe:
          #   httpGet:
          #     path: /infra
          #     port: 8080
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /infra
          #     port: 8080
          #   initialDelaySeconds: 40
          #   periodSeconds: 15
