apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ygss-prod

resources:
  - ../../base

patchesStrategicMerge:
  - patch-backend.yml
  - patch-ingress.yml

images:
  - name: ygss-backend
    newTag: v${BUILD_NUMBER}
  - name: ygss-ai
    newTag: v${BUILD_NUMBER}

commonLabels:
  env: production

replicas:
  - name: backend
    count: 1
  - name: ai
    count: 1