apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP