apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/deployment.yml
  - backend/service.yml
  - backend/configmap.yml
  - shared/ingress.yml

commonLabels:
  app: ygss-backend
  version: v1

images:
  - name: ygss-backend
    newTag: latest